version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: kacsa
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - backend-network

  rest-api:
    build:
      context: .
      dockerfile: Dockerfile.rest-api
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://user:kacsa@postgres:5432/backend_db?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - backend-network

  ws-api:
    build:
      context: .
      dockerfile: Dockerfile.ws-api
    ports:
      - "8081:8081"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://user:kacsa@postgres:5432/backend_db?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - backend-network

volumes:
  postgres_data:
  redis_data:

networks:
  backend-network:
    driver: bridge